{{- $ca := genCA "admission-controller-ca" 3650 }}
{{- $cn := printf "%s-%s" .Release.Name .Chart.Name }}
{{- $altName1 := printf "%s-cluster-agent.%s" "datadog-local" .Release.Namespace }}
{{- $altName2 := printf "%s-cluster-agent.%s.svc" "datadog-local" .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}

apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "datadog.fullname" . }}
  labels:
    app: {{ template "datadog.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
webhooks:
- name: {{ template "datadog.fullname" . }}.cluster-agent-mutating-webhook.local
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: {{ template "datadog.fullname" . }}-cluster-agent
      namespace: {{ .Release.Namespace }}
      path: "/mutate"
      port: 5004
  failurePolicy: {{ .Values.clusterAgent.admissionControllerFailurePolicy }}
  rules:
    - operations: [ "CREATE" ]
      apiGroups: ["apps", ""]
      apiVersions: ["v1"]
      resources: ["deployments","services","pods"]

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "datadog.fullname" . }}-cluster-agent-certs
  labels:
    app: {{ template "datadog.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  cert.pem: {{ b64enc $cert.Cert }}
  key.pem: {{ b64enc $cert.Key }}
