apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "datadog.fullname" . }}-cluster-agent-mutating-webhook-cfg
  labels:
    app: {{ template "datadog.fullname" . }}-cluster-agent-mutating-webhook
webhooks:
  - name: {{ template "datadog.fullname" . }}.cluster-agent-mutating-webhook.local
    clientConfig:
      service:
        name: {{ template "datadog.fullname" . }}-cluster-agent
        namespace: default
        path: "/mutate"
        port: 5007
      caBundle: {{ .Values.clusterAgent.admissionControllerCA }}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","services","pods"]
    namespaceSelector:
      matchLabels:
        admission-webhook-example: enabled

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "datadog.fullname" . }}-new-certs
  labels:
    app: {{ template "datadog.fullname" . }}-cluster-agent
    chart: {{ template "datadog-agent.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "datadog-cluster-agent.gen-certs" . ) | indent 2 }}
