#kind: Role
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  namespace: default
#  name: {{ template "datadog.fullname" . }}-admission-controller-hook-9
#rules:
#  - apiGroups: [""]
#    resources: ["configmaps"]
#    verbs: ["get"]
#---
#kind: RoleBinding
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  name: {{ template "datadog.fullname" . }}-admission-controller-hook-9
#  namespace: kube-system
#subjects:
#  - kind: "ServiceAccount"
#    name: {{ template "datadog.fullname" . }}-admission-controller-hook-1
#roleRef:
#  kind: Role
#  name: extension-apiserver-authentication-reader
#  apiGroup: rbac.authorization.k8s.io
#

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wardle-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: {{ template "datadog.fullname" . }}-admission-controller-hook-1
    namespace: default
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "datadog.fullname" . }}-admission-controller-hook-1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-pods
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - patch
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: {{ template "datadog.fullname" . }}-admission-controller-hook-1
roleRef:
  kind: Role
  name: modify-pods
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "datadog.fullname" . }}-admission-controller-hook-2
rules:
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
      - certificatesigningrequests/approval
    verbs:
      - create
      - update
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "datadog.fullname" . }}-admission-controller-hook-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "datadog.fullname" . }}-admission-controller-hook-2
subjects:
  - kind: ServiceAccount
    name: {{ template "datadog.fullname" . }}-admission-controller-hook-1
    namespace: {{ .Release.Namespace }}
#    namespace: {{ template "datadog.fullname" . }}-admission-controller-hook-1

#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: {{ template "datadog.fullname" . }}-admission-controller-hook-1
#spec:
#  serviceAccountName: {{ template "datadog.fullname" . }}-admission-controller-hook-1
#  containers:
#    - name: internal-kubectl
#      image: trstringer/internal-kubectl:latest


#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: example-sa
#---
#kind: Role
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  namespace: default
#  name: example-role
#rules:
#  - apiGroups: [""] # "" indicates the core API group
#    resources: ["pods"]
#    verbs: ["get", "watch", "list"]
#---
#kind: RoleBinding
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  name: example-role-binding
#  namespace: default
#subjects:
#  - kind: "ServiceAccount"
#    name: example-sa
#roleRef:
#  kind: Role
#  name: example-role
#  apiGroup: rbac.authorization.k8s.io
#---
#kind: Pod
#apiVersion: v1
#metadata:
#  name: example-pod
#spec:
#  serviceAccountName: example-sa
#  containers:
#    - name: secret-access-container
#      image: example-image






#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  annotations:
#    rbac.authorization.kubernetes.io/autoupdate: "true"
#  creationTimestamp: null
#  labels:
#    kubernetes.io/bootstrapping: rbac-defaults
#  name: {{ template "datadog.fullname" . }}-admission-controller-hook-1
#rules:
#  - apiGroups:
#      - certificates.k8s.io
#    resources:
#      - certificatesigningrequests
#    verbs:
#      - create
#      - delete
#      - get
#      - list
#      - watch
#  - apiGroups: [""]
#    resources: ["pods"]
#    verbs: ["create","delete","get","list","patch","update","watch"]
#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  labels:
#    app: "{{ template "datadog.fullname" . }}"
#    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
#    heritage: {{ .Release.Service | quote }}
#    release: {{ .Release.Name | quote }}
#    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
#    app.kubernetes.io/name: "{{ template "datadog.fullname" . }}"
#    app.kubernetes.io/instance: {{ .Release.Name | quote }}
#    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
#    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
#  name: {{ template "datadog.fullname" . }}-admission-controller-hook-1
#---
#apiVersion: {{ template "rbac.apiVersion" . }}
#kind: ClusterRoleBinding
#metadata:
#  labels:
#    app: "{{ template "datadog.fullname" . }}"
#    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
#    release: {{ .Release.Name | quote }}
#    heritage: {{ .Release.Service | quote }}
#    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
#    app.kubernetes.io/name: "{{ template "datadog.fullname" . }}"
#    app.kubernetes.io/instance: {{ .Release.Name | quote }}
#    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
#    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
#  name: {{ template "datadog.fullname" . }}-admission-controller-hook-1
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: {{ template "datadog.fullname" . }}-admission-controller-hook-1
#subjects:
#  - kind: ServiceAccount
#    name: {{ template "datadog.fullname" . }}
##    namespace: {{ template "datadog.fullname" . }}-admission-controller-hook-1
#    namespace: default








---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-install-job"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
#    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-post-install-job"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
#      serviceAccountName: internal-kubectl
      serviceAccountName: {{ template "datadog.fullname" . }}-admission-controller-hook-1
      containers:
#        - name: internal-kubectl
#          image: trstringer/internal-kubectl:latest
#          command: ["/bin/sleep", "3600" ]

##      serviceAccountName: {{ template "datadog.fullname" . }}-admission-controller-hook-1
##      serviceAccountName: example-sa
#      serviceAccountName: internal-kubectl
#      containers:
##        - name: post-install-job
##          image: "alpine:3.3"
##          command: ["/bin/sleep","10"]
#        - name: test-sleep # TODO remove me
#          image: "marcotc/k8s-webhook-cert-manager"
#          command: ["/bin/sleep", "3600" ]
#        - name: test-sleep # TODO remove me
#          image: "marcotc/k8s-webhook-cert-manager"
#          command: ["kubectl", "get", "pods" ]
        - name: create-webhook-certificate
          image: "marcotc/k8s-webhook-cert-manager"
          command: ["./generate_certificate.sh", "--service", {{ template "datadog.fullname" . }}-cluster-agent, "--webhook", {{ template "datadog.fullname" . }}-cluster-agent-mutating-webhook, "--secret", {{ template "datadog.fullname" . }}-admission-cert, "--namespace", {{ .Release.Namespace }} ]
#      ./generate_certificate.sh --service datadog-local-cluster-agent --webhook datadog-local-cluster-agent-mutating-webhook --secret  datadog-local-admission-cert --namespace default

