{{- $ca := genCA "datadog-admission-controller-ca" 10000 }}
{{- $cn := printf "%s-cluster-agent" (include "datadog.fullname" .) -}}
{{- $altName1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 10000 $ca }}

apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "datadog.fullname" . }}
  labels:
    app: {{ template "datadog.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
webhooks:
- name: {{ template "datadog.fullname" . }}.cluster-agent-mutating-admissioncontroller.local
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: {{ template "datadog.fullname" . }}-cluster-agent
      namespace: {{ .Release.Namespace }}
      path: "/mutate"
      port: 5004
  rules:
    - operations: [ "CREATE" ]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "datadog.fullname" . }}-cluster-agent-admission-controller-certificate
  labels:
    app: {{ template "datadog.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  cert.pem: {{ b64enc $cert.Cert }}
  key.pem: {{ b64enc $cert.Key }}
